w7--backend/notes/mailers-in-class/config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'login/new'
  get 'login/create'
  post 'login/create'
  get 'login/destroy'

  root 'users#index'
end

w7--backend/notes/mailers-in-class/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

w7--backend/notes/mailers-in-class/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
  end
end

w7--backend/notes/mailers-in-class/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome(@user).deliver_now
      redirect_to login_new_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

  private
   def user_params
    params.require(:user).permit(:name, :email, :password)
   end
end

w7--backend/notes/mailers-in-class/app/helpers/login_helper.rb
module LoginHelper
end

w7--backend/notes/mailers-in-class/app/helpers/users_helper.rb
module UsersHelper
end

w7--backend/notes/mailers-in-class/app/views/login/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

w7--backend/notes/mailers-in-class/app/views/login/destroy.html.erb
<h1>Login#destroy</h1>
<p>Find me in app/views/login/destroy.html.erb</p>

w7--backend/notes/mailers-in-class/app/views/login/new.html.erb
<h1>Login#new</h1>
<p>Find me in app/views/login/new.html.erb</p>

<div class="login-form">
 <%= form_tag login_create_path do %>
    <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    </div>
    <div>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    </div>
    <div>
      <%= button_to :submit %>
    </div>

 <% end %>
</div>

w7--backend/notes/mailers-in-class/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

w7--backend/notes/mailers-in-class/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

w7--backend/notes/mailers-in-class/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<div class="registration-form">
 <%= form_for @user do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </div>
    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <div>
      <%= f.submit %>
    </div>

 <% end %>
</div>

w7--backend/notes/mailers-in-class/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>