w6--backend/notes/holidays/config/routes.rb
Rails.application.routes.draw do
  resources :holidays
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

w6--backend/notes/holidays/app/models/holiday.rb
class Holiday < ApplicationRecord
end

w6--backend/notes/holidays/app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end
  # with ajax it looks like this:
  # def create
  #   @holiday = Holiday.new(holiday_params)
  #   unless @@holiday.save
  #     render :new
  #   end
  # end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:name, :observed_on, :country_of_origin)
    end
end

w6--backend/notes/holidays/app/helpers/holidays_helper.rb
module HolidaysHelper
end

w6--backend/notes/holidays/app/views/holidays/_form.html.erb
<%= form_with(model: @holiday, remote: true) do |form| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :observed_on %>
    <%= form.date_select :observed_on %>
  </div>

  <div class="field">
    <%= form.label :country_of_origin %>
    <%= form.text_field :country_of_origin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w6--backend/notes/holidays/app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

w6--backend/notes/holidays/app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Holidays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Observed on</th>
      <th>Country of origin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.observed_on %></td>
        <td><%= holiday.country_of_origin %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path, remote:true %>

<div id="form--new"></div>

w6--backend/notes/holidays/app/views/holidays/new.js.erb
$('#form--new').html("<%= escape_javascript (render 'form') %>");

w6--backend/notes/holidays/app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Observed on:</strong>
  <%= @holiday.observed_on %>
</p>

<p>
  <strong>Country of origin:</strong>
  <%= @holiday.country_of_origin %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>

w6--backend/notes/holidays/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Holidays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>