w6--backend/notes/amy-freeshelf/config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]
  resource :session, only: [:new, :create, :destroy]

  resources :books do
    resources :checkouts, only: [:new, :create, :destroy]
  end

  root 'books#index'
end

w6--backend/notes/amy-freeshelf/app/models/book.rb
class Book < ApplicationRecord
  validates :title, :url, presence: true, uniqueness: true

  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :checkouts
  has_many :users, through: :checkouts

  def checked_out?
    self.checkouts.exists?
  end

end

w6--backend/notes/amy-freeshelf/app/models/checkout.rb
class Checkout < ApplicationRecord

  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :book_id
end

w6--backend/notes/amy-freeshelf/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, :email, presence: true
  validates :email, uniqueness: true, case_sensitive: false
  validates :password, confirmation: true

  has_many :books_created
  has_many :checkouts
  has_many :books_checked_out, through: :checkouts
end

w6--backend/notes/amy-freeshelf/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

protected
  def current_user
    # Putting this method here gives us access to it in every controller that inherits from it
    # Because we stored the user_id in session#create in the SessionsController,
    # we have access to it in the session, which extends across requests
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

w6--backend/notes/amy-freeshelf/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.creator = current_user || User.find_by_email(params[:email])
    if @book.save
      @books = Book.all
      render :index
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    @checkout = Checkout.new if !@book.checked_out?
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book successfully updated!"
      flash[:msg] = "success"
      redirect_to books_url
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    title = @book.title
    if @book.destroy
      flash[:notice] = "#{title} has been deleted!"
      flash[:msg] = "warning"
    else
    flash[:notice] = "There was a problem deleting #{title}."
    flash[:msg] = "warning"
    end
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :url, :description)
    end
end

w6--backend/notes/amy-freeshelf/app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @user = current_user
    @checkout = Checkout.new
  end

  def create
    user = User.find_by_email(params[:email]) || User.find_by_id(params[:user_id])
    book = Book.find(params[:book_id])
    if book.checked_out?
      flash[:notice] = "#{book.title} is already checked out."
      flash[:msg] = 'alert'
      redirect_to book_url(book)
      return
    end
    @checkout = Checkout.new(user_id: params[:user_id], book_id: book.id)
    if @checkout.save
      flash[:msg] = "info"
      flash[:notice] = "#{book.title} has been checked out to you"
    end
    redirect_to book_url(book)
  end

  def delete
  end

  private
  def checkout_params
    params.require(:checkout).permit([:email, :book_id])
  end

end

w6--backend/notes/amy-freeshelf/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # this action doesn't need to do anything except render the template
    # the new template is the login form
  end

  def create
    @user ||= User.find_by_email(params[:email])
    # the authenticate method comes from bcrypt
    # takes the password typed into the login form as an argument
    if @user && @user.authenticate(params[:password])
      # if we have a match for the user and password,
      # store the user_id in the session.
      # This is programmatically "logging in".
      # since it exists in the session, which extends across requests, it lets us identify a "current user"
      # see that method in ApplicationController
      session[:user_id] = @user.id
      flash[:msg] = "success"
      redirect_to root_path, notice: "You are now logged in"
    else
      flash[:msg] = "danger"
      redirect_to new_session_path, notice: "There was a problem logging you in. Please try again."
    end
  end

  def destroy
    # To programmatically "log out", we remove the user_id from the session.
    # Here we are doing that by setting it to nil.
    session[:user_id] = nil
    flash[:msg] = "info"
    redirect_to root_url, notice: "You've been logged out"
  end

end

w6--backend/notes/amy-freeshelf/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_user_exists, only: :create

  def new
    redirect_to user_path(current_user) if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:msg] = "success"
      render :show, notice: "Welcome! You are logged in."
    else
      render :new, notice: "Whoops, something went wrong. Please try again."
    end
  end

  def show
    @user = User.find(params[:id])
    @books_created = @user.books_created
    @books_checked_out = @user.books_checked_out
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Your account has been deleted."
      flash[:msg] = "warning"
    else
      flash[:notice] = "Something went wrong."
      flash[:msg] = "warning"
    end
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def check_if_user_exists
    user = User.find_by_email(params[:user][:email])
    if user
    flash[:msg] = "warning"
    redirect_to new_session_url, notice: "An account with that email address already exists. Please log in."
    end
  end
end

w6--backend/notes/amy-freeshelf/app/helpers/books_helper.rb
module BooksHelper
end

w6--backend/notes/amy-freeshelf/app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

w6--backend/notes/amy-freeshelf/app/helpers/sessions_helper.rb
module SessionsHelper
end

w6--backend/notes/amy-freeshelf/app/views/layouts/_header.html.erb
<div class="page-header">
  <%= link_to root_path, class: "header__link" do %>
  <div class="emojii--book">📖</div>
    <h1 class="page-header--title">FreeShelf</h1>
  <% end %>
  <div class="nav-controls">
    <%#=
      link_to_if(current_user, "Log Out", {url: session_url, method: :delete}, class: "btn btn-outline-light") do
        link_to("Log In", new_session_path, class: "btn btn-outline-light")
      end
    %>
    <% if current_user %>
      <%= link_to('Log Out', session_path, method: :delete, class: "btn btn-outline-light") %>
    <% else %>
      <%= link_to('Sign up', new_user_path, class: "btn btn-outline-light")%>
      <%= link_to('Log In', new_session_path, class: "btn btn-outline-light")%>
    <% end %>
    <%= link_to 'New Book', new_book_path, class: "btn btn-outline-light" %>
  </div>
</div>

w6--backend/notes/amy-freeshelf/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmyFreeshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render partial: "layouts/header" %>
    </header>
    <main class="container-fluid">
      <%= yield %>
    </main>
  </body>
</html>

w6--backend/notes/amy-freeshelf/app/views/users/new.html.erb
<h1>Register for FreeShelf</h1>

<% if notice %>
<div class="alert alert-<%= flash[:msg] %>"><%= notice %></div>
<% end %>

  <%= form_with(model: @user, local:true) do |f| %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name, class: "form__label" %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email, class: "form__label" %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password, class: "form__label" %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, class: "form__label" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit 'Register', class: "btn btn-submit" %>
    </div>
  </div>
  <% end %>

w6--backend/notes/amy-freeshelf/app/views/users/show.html.erb
<h2> User Account Page </h2>
<% if notice %>
    <div class="alert alert-<%= flash[:msg] %>" id="home-page-flash"><%= flash[:notice] %></div>
<% end %>
<div class="list">
  <ul class="list-group">
    <li class="list-group-item"><%= @user.name %></li>
    <li class="list-group-item"><%= @user.email %></li>
  </ul>
</div>